# Generated by Django 3.2.6 on 2022-02-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_collation='utf8_general_ci', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=20)),
                ('classname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblprofile',
            },
        ),
    ]
