# Generated by Django 3.2.6 on 2022-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220215_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
